base: 'https://typo311website.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
    websiteTitle: ''
  -
    title: Deutsch
    enabled: true
    base: /de/
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    websiteTitle: 'Wissenschaft & Technologie'
    navigationTitle: DE
    hreflang: de-de
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
  -
    title: Polski
    enabled: true
    base: /pl/
    typo3Language: pl
    locale: pl_PL
    iso-639-1: pl
    websiteTitle: 'Nauka i Technologia'
    navigationTitle: PL
    hreflang: pl-pl
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: pl
    languageId: 2
rootPageId: 4
websiteTitle: Survival
